git:
  depth: 1

matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      addons:
        apt:
          packages:
            - realpath
            - binfmt-support
      language: cpp
      env: BUILD_TESTS=ON PYTHON_BINDINGS=NO ARCH=aarch64
      before_install: tests/travis/lnx_docker_setup.sh
      script: tests/travis/lnx_docker.sh
