git:
  depth: 1

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      language: cpp
      cache:
        - ccache
      env: PYTHON_BINDINGS=YES PYTHON_VERSION=2.7 PYTHON_EXECUTABLE=/usr/bin/python2.7 BUILD_TESTS=ON
      before_install: tests/travis/osx_setup.sh
      script: tests/travis/osx.sh
    - os: osx
      osx_image: xcode10.1
      language: cpp
      cache:
        - ccache
      env: PYTHON_BINDINGS=YES PYTHON_VERSION=3.6 PYTHON_EXECUTABLE=/usr/local/bin/python3 BUILD_TESTS=ON
      before_install: tests/travis/osx_setup.sh
      script: tests/travis/osx.sh
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - ninja-build
            - llvm-8-dev
            - llvm-8-tools
            - clang-8
            - libclang-8-dev
            - python3-dev
            - libpython3-dev
            - python3-pip
      language: cpp
      cache:
        - ccache
      env: PYTHON_VERSION=2.7
      before_install: tests/travis/lnx_setup.sh
      script: tests/travis/lnx_py.sh
#    - os: linux
#      dist: xenial
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-7
#          packages:
#            - ninja-build
#            - llvm-7-dev
#            - llvm-7-tools
#            - clang-7
#            - libclang-7-dev
#            - python3-dev
#            - libpython3-dev
#            - python3-pip
#      language: cpp
#      cache:
#        - ccache
#      env: PYTHON_VERSION=3.5 PYTHON_EXECUTABLE=python3
#      before_install: tests/travis/lnx_setup.sh
#      script: tests/travis/lnx_py.sh
#    - os: linux
#      sudo: required
#      services:
#        - docker
#      addons:
#        apt:
#          packages:
#            - realpath
#            - binfmt-support
#      language: cpp
#      env: BUILD_TESTS=ON PYTHON_BINDINGS=NO ARCH=aarch64
#      before_install: tests/travis/lnx_docker_setup.sh
#      script: tests/travis/lnx_docker.sh
